#ifndef RABIN_MAX_BLOCK_SIZE
#define RABIN_MAX_BLOCK_SIZE 4
#endif

#ifndef RABIN_MIN_BLOCK_SIZE
#define RABIN_MIN_BLOCK_SIZE 2
#endif

#ifndef RABIN_POLYNOMIAL_AVG_BLOCK_SIZE
#define RABIN_POLYNOMIAL_AVG_BLOCK_SIZE 0xff
#endif

#ifndef RABIN_POLYNOMIAL_REM
#define RABIN_POLYNOMIAL_REM 257
#endif

#ifndef RABIN_POLYNOMIAL_WIN_SIZE
#define RABIN_POLYNOMIAL_WIN_SIZE 32
#endif

#ifndef RABIN_POLYNOMIAL_MIN_WIN_SIZE
#define RABIN_POLYNOMIAL_MIN_WIN_SIZE 16
#endif

#ifndef RABIN_POLYNOMIAL_MAX_WIN_SIZE
#define RABIN_POLYNOMIAL_MAX_WIN_SIZE 64
#endif

// # of bytes to read at a time when reading through files
#ifndef RABIN_FILE_READ_BUF_SIZE
#define RABIN_FILE_READ_BUF_SIZE 1048576
#endif